namespace Swapi.Service.UnitTests
{
    public static class ContentSamples
    {
        public const string PeopleContent = @"{""name"":""C-3PO"",""height"":""167"",""mass"":""75"",""hair_color"":""n/a"",""skin_color"":""gold"",""eye_color"":""yellow"",""birth_year"":""112BBY"",""gender"":""n/a"",""homeworld"":""http://swapi.dev/api/planets/1/"",""films"":[""http://swapi.dev/api/films/1/"",""http://swapi.dev/api/films/2/"",""http://swapi.dev/api/films/3/"",""http://swapi.dev/api/films/4/"",""http://swapi.dev/api/films/5/"",""http://swapi.dev/api/films/6/""],""species"":[""http://swapi.dev/api/species/2/""],""vehicles"":[],""starships"":[],""created"":""2014-12-10T15:10:51.357000Z"",""edited"":""2014-12-20T21:17:50.309000Z"",""url"":""http://swapi.dev/api/people/2/""}";
        
        public const string PeopleSearchResultContent = @"{""count"":2,""next"":null,""previous"":null,""results"":[{""name"":""Luke Skywalker"",""height"":""172"",""mass"":""77"",""hair_color"":""blond"",""skin_color"":""fair"",""eye_color"":""blue"",""birth_year"":""19BBY"",""gender"":""male"",""homeworld"":""http://swapi.dev/api/planets/1/"",""films"":[""http://swapi.dev/api/films/1/"",""http://swapi.dev/api/films/2/"",""http://swapi.dev/api/films/3/"",""http://swapi.dev/api/films/6/""],""species"":[],""vehicles"":[""http://swapi.dev/api/vehicles/14/"",""http://swapi.dev/api/vehicles/30/""],""starships"":[""http://swapi.dev/api/starships/12/"",""http://swapi.dev/api/starships/22/""],""created"":""2014-12-09T13:50:51.644000Z"",""edited"":""2014-12-20T21:17:56.891000Z"",""url"":""http://swapi.dev/api/people/1/""},{""name"":""Luminara Unduli"",""height"":""170"",""mass"":""56.2"",""hair_color"":""black"",""skin_color"":""yellow"",""eye_color"":""blue"",""birth_year"":""58BBY"",""gender"":""female"",""homeworld"":""http://swapi.dev/api/planets/51/"",""films"":[""http://swapi.dev/api/films/5/"",""http://swapi.dev/api/films/6/""],""species"":[""http://swapi.dev/api/species/29/""],""vehicles"":[],""starships"":[],""created"":""2014-12-20T16:45:53.668000Z"",""edited"":""2014-12-20T21:17:50.455000Z"",""url"":""http://swapi.dev/api/people/64/""}]}";
        
        public const string PlanetContent = @"{""name"":""Alderaan"",""rotation_period"":""24"",""orbital_period"":""364"",""diameter"":""12500"",""climate"":""temperate"",""gravity"":""1 standard"",""terrain"":""grasslands, mountains"",""surface_water"":""40"",""population"":""2000000000"",""residents"":[""http://swapi.dev/api/people/5/"",""http://swapi.dev/api/people/68/"",""http://swapi.dev/api/people/81/""],""films"":[""http://swapi.dev/api/films/1/"",""http://swapi.dev/api/films/6/""],""created"":""2014-12-10T11:35:48.479000Z"",""edited"":""2014-12-20T20:58:18.420000Z"",""url"":""http://swapi.dev/api/planets/2/""}";

        public const string PlanetSearchResultContent =
            @"{""count"":2,""next"":null,""previous"":null,""results"":[{""name"":""Aleen Minor"",""rotation_period"":""unknown"",""orbital_period"":""unknown"",""diameter"":""unknown"",""climate"":""unknown"",""gravity"":""unknown"",""terrain"":""unknown"",""surface_water"":""unknown"",""population"":""unknown"",""residents"":[""http://swapi.dev/api/people/47/""],""films"":[],""created"":""2014-12-20T09:52:23.452000Z"",""edited"":""2014-12-20T20:58:18.483000Z"",""url"":""http://swapi.dev/api/planets/38/""},{""name"":""Kalee"",""rotation_period"":""23"",""orbital_period"":""378"",""diameter"":""13850"",""climate"":""arid, temperate, tropical"",""gravity"":""1"",""terrain"":""rainforests, cliffs, canyons, seas"",""surface_water"":""unknown"",""population"":""4000000000"",""residents"":[""http://swapi.dev/api/people/79/""],""films"":[],""created"":""2014-12-20T19:43:51.278000Z"",""edited"":""2014-12-20T20:58:18.523000Z"",""url"":""http://swapi.dev/api/planets/59/""}]}";
    }
}
